version: "3.8"

services:
  backend:
    build:
      context: ./backend-fiber
      dockerfile: Dockerfile
    container_name: moodshift-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - PORT=8080
      - CORS_ALLOW_ORIGINS=https://moodshift.fuadfakhruz.id
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=https://moodshift.fuadfakhruz.id/api/v1/auth/callback
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - moodshift-network
    labels:
      - "dokploy.enable=true"
      - "dokploy.healthcheck.path=/health"
      - "dokploy.port=8080"
      - "dokploy.public=true"
      - "dokploy.domain=api.moodshift.fuadfakhruz.id"

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    container_name: moodshift-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - moodshift-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      - "dokploy.enable=true"
      - "dokploy.port=80"
      - "dokploy.public=true"
      - "dokploy.domain=moodshift.fuadfakhruz.id"

networks:
  moodshift-network:
    driver: bridge
