version: "3.8"

services:
  backend:
    build:
      context: ./backend-fiber
      dockerfile: Dockerfile
    container_name: moodshift-backend
    restart: unless-stopped
    ports:
      - "9898:8080"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - PORT=8080
      - CORS_ALLOW_ORIGINS=http://localhost:8080
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=http://localhost:8080/api/v1/auth/callback
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - moodshift-network

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    container_name: moodshift-frontend
    restart: unless-stopped
    ports:
      - "8989:80"
    networks:
      - moodshift-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  moodshift-network:
    driver: bridge
